// flow-typed signature: c7b9915d07bcd1c0c9e98014082ba6f4
// flow-typed version: <<STUB>>/react-loadable_v4.0.3/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-loadable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-loadable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-loadable/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-loadable/lib/index.js' {
  declare module.exports: $Exports<'react-loadable/lib/index'>;
}
