// flow-typed signature: 7845cca93c73dcd20ee2de43c89a3e92
// flow-typed version: <<STUB>>/sanitize.css_v4.1.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sanitize.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sanitize.css' {
  declare module.exports: any;
}
